addEventListener("keydown", keyHandler);

function keyHandler(e) {
    if (e.keyCode == 9) {
        var focused = document.activeElement;
        console.log(focused.value);

        if (focused.value == "lorem 1") {
            focused.value = "Lorem ipsum dolor sit amet, sit omnis possim eu, movet graeco dolorum mel cu. Novum tamquam invidunt vix ea, ex meis iusto sea. In mei tamquam principes. Sit erant omnium vocibus eu. Fugit saperet no his, usu dictas periculis eu, an eripuit perfecto his.";
        } else if (focused.value == "lorem 2") {
            focused.value = "Lorem ipsum dolor sit amet, sit omnis possim eu, movet graeco dolorum mel cu. Novum tamquam invidunt vix ea, ex meis iusto sea. In mei tamquam principes. Sit erant omnium vocibus eu. Fugit saperet no his, usu dictas periculis eu, an eripuit perfecto his.\n\nVitae deleniti luptatum et mei, porro option an vis. Postea noster corrumpit sea ea, ea malis suavitate imperdiet has. Ex lorem numquam nominavi sed, detracto deserunt similique no eos. Mel everti legimus ne. Ea sed altera denique dissentiunt, facer contentiones in usu, usu senserit conceptam in."
        } else if (focused.value == "lorem 3") {
            focused.value = "Lorem ipsum dolor sit amet, sit omnis possim eu, movet graeco dolorum mel cu. Novum tamquam invidunt vix ea, ex meis iusto sea. In mei tamquam principes. Sit erant omnium vocibus eu. Fugit saperet no his, usu dictas periculis eu, an eripuit perfecto his.\n\nVitae deleniti luptatum et mei, porro option an vis. Postea noster corrumpit sea ea, ea malis suavitate imperdiet has. Ex lorem numquam nominavi sed, detracto deserunt similique no eos. Mel everti legimus ne. Ea sed altera denique dissentiunt, facer contentiones in usu, usu senserit conceptam in.\n\nMovet volutpat facilisis et mei, liber noluisse volutpat in mel, nec dicit scaevola sensibus ei. At possit feugiat cum, ut velit oporteat consequat nam. Incorrupte vituperatoribus an eos, sea no meis dictas voluptatum, molestie interesset consectetuer ius no. Te duo errem officiis. Aliquam mandamus periculis sed ne. Id fastidii vituperata sea, no utinam prompta liberavisse eum, vero error fabellas cu qui."
        } else if (focused.value == "lorem 4") { 
            focused.value = "Lorem ipsum dolor sit amet, sit omnis possim eu, movet graeco dolorum mel cu. Novum tamquam invidunt vix ea, ex meis iusto sea. In mei tamquam principes. Sit erant omnium vocibus eu. Fugit saperet no his, usu dictas periculis eu, an eripuit perfecto his.\n\nVitae deleniti luptatum et mei, porro option an vis. Postea noster corrumpit sea ea, ea malis suavitate imperdiet has. Ex lorem numquam nominavi sed, detracto deserunt similique no eos. Mel everti legimus ne. Ea sed altera denique dissentiunt, facer contentiones in usu, usu senserit conceptam in.\n\nMovet volutpat facilisis et mei, liber noluisse volutpat in mel, nec dicit scaevola sensibus ei. At possit feugiat cum, ut velit oporteat consequat nam. Incorrupte vituperatoribus an eos, sea no meis dictas voluptatum, molestie interesset consectetuer ius no. Te duo errem officiis. Aliquam mandamus periculis sed ne. Id fastidii vituperata sea, no utinam prompta liberavisse eum, vero error fabellas cu qui.\n\nIn graece admodum philosophia vim, omnis nusquam dissentiet eam an, sed eu quem solet. Mel fuisset recusabo id, nec unum quidam appetere ea. Cu vel graece copiosae epicurei, ornatus singulis interesset ad vim. Est ne docendi assentior. Augue reprimique at ius. Homero salutatus scriptorem ut sit, duo nostrum gubergren mnesarchum te, nam saepe graeco vivendum no."
        } else if (focused.value == "lorem 5") {
            focused.value = "Lorem ipsum dolor sit amet, sit omnis possim eu, movet graeco dolorum mel cu. Novum tamquam invidunt vix ea, ex meis iusto sea. In mei tamquam principes. Sit erant omnium vocibus eu. Fugit saperet no his, usu dictas periculis eu, an eripuit perfecto his.\n\nVitae deleniti luptatum et mei, porro option an vis. Postea noster corrumpit sea ea, ea malis suavitate imperdiet has. Ex lorem numquam nominavi sed, detracto deserunt similique no eos. Mel everti legimus ne. Ea sed altera denique dissentiunt, facer contentiones in usu, usu senserit conceptam in.\n\nMovet volutpat facilisis et mei, liber noluisse volutpat in mel, nec dicit scaevola sensibus ei. At possit feugiat cum, ut velit oporteat consequat nam. Incorrupte vituperatoribus an eos, sea no meis dictas voluptatum, molestie interesset consectetuer ius no. Te duo errem officiis. Aliquam mandamus periculis sed ne. Id fastidii vituperata sea, no utinam prompta liberavisse eum, vero error fabellas cu qui.\n\nIn graece admodum philosophia vim, omnis nusquam dissentiet eam an, sed eu quem solet. Mel fuisset recusabo id, nec unum quidam appetere ea. Cu vel graece copiosae epicurei, ornatus singulis interesset ad vim. Est ne docendi assentior. Augue reprimique at ius. Homero salutatus scriptorem ut sit, duo nostrum gubergren mnesarchum te, nam saepe graeco vivendum no.\n\nQui in vocent gubergren inciderint, ne suas vitae definitiones mel. Vel suas sensibus senserit ne. Id utinam meliore scaevola vis. Mea no utamur consulatu. In eum error primis. Sit an sale reprehendunt, per clita oportere te. Stet illum utinam et nam, vix veri sonet melius ei."
        }
        if (e.preventDefault) {
            e.preventDefault();
        }
        return false;
    }
}

